// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novacart.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Novacart.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709164241_AddP2Scaffold")]
    partial class AddP2Scaffold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Novacart.Api.Models.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_carts_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_carts_user_id");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_slug");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Apparel",
                            Slug = "apparel"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Home & Living",
                            Slug = "home-living"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Books",
                            Slug = "books"
                        });
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_order_number");

                    b.HasIndex("UserId", "CurrentStatus", "CreatedAt")
                        .HasDatabaseName("idx_orders_user_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_payment_methods_code");

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "stripe",
                            DisplayName = "Credit / Debit Card",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.PaymentWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("idx_payment_webhooks_event_id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("payment_webhooks", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.PriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_price_rules_category_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_price_rules_product_id");

                    b.ToTable("price_rules", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_products_slug");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Premium over-ear headphones with 30-hour battery and adaptive noise cancellation for immersive listening.",
                            IsActive = true,
                            Metadata = "{\"brand\":\"SoundPro\",\"connectivity\":\"Bluetooth 5.3\",\"battery_hours\":30,\"weight_g\":250,\"color\":\"Midnight Black\",\"frequency_response\":\"20Hz–20kHz\",\"driver_size_mm\":40}",
                            Name = "Wireless Noise-Cancelling Headphones",
                            Price = 199.99m,
                            Slug = "wireless-noise-cancelling-headphones",
                            StockQuantity = 45,
                            Tags = new[] { "audio", "wireless", "noise-cancelling", "bluetooth" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "QHD IPS panel with 144Hz refresh rate, 1ms response time, and USB-C power delivery for creatives and gamers.",
                            IsActive = true,
                            Metadata = "{\"brand\":\"ViewMax\",\"resolution\":\"3440x1440\",\"refresh_rate_hz\":144,\"panel_type\":\"IPS\",\"response_time_ms\":1,\"ports\":\"2x HDMI, 1x DisplayPort, 2x USB-C\",\"size_inches\":34}",
                            Name = "34\" Ultrawide Curved Monitor",
                            Price = 649.00m,
                            Slug = "ultrawide-curved-monitor-34",
                            StockQuantity = 12,
                            Tags = new[] { "monitor", "ultrawide", "gaming", "usb-c" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Compact TKL layout with hot-swap switches, per-key RGB, and aluminium top plate. Cherry MX Red switches included.",
                            IsActive = true,
                            Metadata = "{\"brand\":\"KeyForge\",\"layout\":\"TKL (80%)\",\"switch_type\":\"Cherry MX Red\",\"backlight\":\"Per-key RGB\",\"connectivity\":\"USB-C detachable\",\"material\":\"Aluminium top plate\",\"hot_swap\":true}",
                            Name = "Tenkeyless Mechanical Keyboard",
                            Price = 149.95m,
                            Slug = "mechanical-keyboard-tkl",
                            StockQuantity = 30,
                            Tags = new[] { "keyboard", "mechanical", "rgb", "gaming", "compact" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "100% Australian merino wool — naturally temperature-regulating, itch-free, and machine washable. A wardrobe staple.",
                            IsActive = true,
                            Metadata = "{\"material\":\"100% Australian Merino Wool\",\"sizes\":[\"XS\",\"S\",\"M\",\"L\",\"XL\",\"XXL\"],\"colors\":[\"Oatmeal\",\"Navy\",\"Forest Green\",\"Charcoal\"],\"fit\":\"Regular\",\"care\":\"Machine wash cold, lay flat to dry\",\"origin\":\"Australia\"}",
                            Name = "Merino Wool Crew-Neck Sweater",
                            Price = 89.00m,
                            Slug = "merino-wool-crew-neck-sweater",
                            StockQuantity = 80,
                            Tags = new[] { "wool", "merino", "knitwear", "sustainable", "unisex" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Stretch-cotton chinos with a clean slim silhouette — smart enough for the office, comfortable enough for the weekend.",
                            IsActive = true,
                            Metadata = "{\"material\":\"97% Cotton, 3% Elastane\",\"sizes\":[\"28\",\"30\",\"32\",\"34\",\"36\",\"38\"],\"inseam_options\":[\"30\\\"\",\"32\\\"\",\"34\\\"\"],\"colors\":[\"Stone\",\"Navy\",\"Olive\",\"Charcoal\"],\"fit\":\"Slim\",\"care\":\"Machine wash 30°C\"}",
                            Name = "Slim-Fit Chino Pants",
                            Price = 69.99m,
                            Slug = "slim-fit-chino-pants",
                            StockQuantity = 120,
                            Tags = new[] { "pants", "chino", "slim-fit", "smart-casual" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Three artisan soy-wax candles in a gift-ready box — Cedar & Amber, Linen & Sea Salt, and Bergamot & White Tea.",
                            IsActive = true,
                            Metadata = "{\"wax_type\":\"100% natural soy\",\"burn_time_hours\":35,\"scents\":[\"Cedar & Amber\",\"Linen & Sea Salt\",\"Bergamot & White Tea\"],\"container\":\"Glass tumbler\",\"weight_g\":200,\"wick\":\"Cotton braided\",\"quantity_in_pack\":3}",
                            Name = "Hand-Poured Soy Candle Set (3-pack)",
                            Price = 49.95m,
                            Slug = "hand-poured-soy-candle-set",
                            StockQuantity = 60,
                            Tags = new[] { "candle", "soy-wax", "gift", "scented", "handmade" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Handcrafted from sustainably sourced Australian black walnut. Juice groove, hanging hole, and oiled finish included.",
                            IsActive = true,
                            Metadata = "{\"material\":\"Solid Australian Black Walnut\",\"dimensions_cm\":\"40 x 25 x 2\",\"finish\":\"Food-safe mineral oil\",\"features\":[\"Juice groove\",\"Hanging hole\"],\"care\":\"Hand wash only, re-oil monthly\",\"origin\":\"Australia\"}",
                            Name = "Solid Walnut Serving Board",
                            Price = 75.00m,
                            Slug = "walnut-serving-board",
                            StockQuantity = 25,
                            Tags = new[] { "wood", "walnut", "kitchen", "serving", "handmade", "sustainable" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Pre-washed French linen that gets softer with every wash. Breathable and naturally thermoregulating for year-round comfort.",
                            IsActive = true,
                            Metadata = "{\"material\":\"100% French Linen\",\"size\":\"Queen (210x210cm)\",\"colors\":[\"White\",\"Sage\",\"Dusk Blue\",\"Natural\"],\"thread_count\":\"N/A (woven linen)\",\"care\":\"Machine wash 40°C, tumble dry low\",\"pillowcases_included\":2}",
                            Name = "Stonewashed Linen Duvet Cover — Queen",
                            Price = 189.00m,
                            Slug = "linen-duvet-cover-queen",
                            StockQuantity = 18,
                            Tags = new[] { "linen", "bedding", "duvet", "sustainable", "french-linen" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "Hand-stitched full-grain cowhide wallet with 6 card slots, a bill compartment, and RFID-blocking lining.",
                            IsActive = true,
                            Metadata = "{\"material\":\"Full-grain cowhide leather\",\"card_slots\":6,\"has_bill_compartment\":true,\"rfid_blocking\":true,\"colors\":[\"Tan\",\"Dark Brown\",\"Black\"],\"dimensions_cm\":\"9.5 x 11 (open)\",\"weight_g\":65}",
                            Name = "Full-Grain Leather Bi-Fold Wallet",
                            Price = 64.95m,
                            Slug = "full-grain-leather-wallet",
                            StockQuantity = 55,
                            Tags = new[] { "leather", "wallet", "accessories", "rfid", "handmade" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "12oz natural canvas tote with reinforced stitching, internal zip pocket, and a padded laptop sleeve up to 14\".",
                            IsActive = true,
                            Metadata = "{\"material\":\"12oz natural cotton canvas\",\"laptop_sleeve\":\"Up to 14\\\"\",\"internal_pockets\":2,\"external_pockets\":1,\"shoulder_strap_drop_cm\":28,\"capacity_litres\":20,\"colors\":[\"Natural\",\"Black\",\"Olive\"]}",
                            Name = "Heavy-Canvas Tote Bag",
                            Price = 39.00m,
                            Slug = "canvas-tote-bag-natural",
                            StockQuantity = 90,
                            Tags = new[] { "tote", "canvas", "sustainable", "laptop", "everyday" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "The classic guide to software craftsmanship — updated for modern development with new topics, tips, and exercises.",
                            IsActive = true,
                            Metadata = "{\"author\":\"David Thomas, Andrew Hunt\",\"publisher\":\"Pragmatic Bookshelf\",\"edition\":\"20th Anniversary\",\"pages\":352,\"isbn\":\"978-0135957059\",\"format\":[\"Paperback\",\"eBook\"],\"language\":\"English\",\"year\":2019}",
                            Name = "The Pragmatic Programmer (20th Anniversary Ed.)",
                            Price = 59.95m,
                            Slug = "the-pragmatic-programmer-20th",
                            StockQuantity = 40,
                            Tags = new[] { "programming", "software", "career", "bestseller" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "AUD",
                            Description = "James Clear's #1 bestseller on building good habits and breaking bad ones — backed by science and packed with practical strategies.",
                            IsActive = true,
                            Metadata = "{\"author\":\"James Clear\",\"publisher\":\"Random House Business\",\"pages\":320,\"isbn\":\"978-1847941831\",\"format\":[\"Paperback\",\"Hardcover\",\"eBook\",\"Audiobook\"],\"language\":\"English\",\"year\":2018}",
                            Name = "Atomic Habits",
                            Price = 29.99m,
                            Slug = "atomic-habits",
                            StockQuantity = 100,
                            Tags = new[] { "self-help", "habits", "productivity", "bestseller" },
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard shopper",
                            Name = "customer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Store administrator",
                            Name = "admin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "System administrator",
                            Name = "sysadmin"
                        });
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDefaultBilling")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefaultShipping")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_addresses_user_id");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("idx_wishlist_user_product");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Cart", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.CartItem", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novacart.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Category", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Order", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novacart.Api.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Payment", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novacart.Api.Models.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.PaymentWebhook", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.PriceRule", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Novacart.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Product", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.UserAddress", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.UserRole", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novacart.Api.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.WishlistItem", b =>
                {
                    b.HasOne("Novacart.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novacart.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Novacart.Api.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
